### PR TITLE
fix(java): return fury to pooled which get from

### PR DESCRIPTION
**Pull request by MrChang0**
## What does this PR do?

incase of pooledCache expired from cache, and fury will return to another pooledCache.
so we save pooledCache instead of get from cache.

## Does this PR introduce any user-facing change?

- [ ] Does this PR introduce any public API change?
- [ ] Does this PR introduce any binary protocol compatibility change?

### CODE REVIEW

**Review by chaokunyang — APPROVED** [review]
LGTM

**Comment by juliojgd** [comment]
This PR os introducing a breaking change in the API, right? By rethrowing exceptions that were not rethrown before.

**Comment by chaokunyang** [comment]
Hi, @juliojgd , could you elaborate more? I don't see API changes

**Comment by juliojgd** [comment]
Sure. This new throw sentence, not present before:
image

Makes that (1) is a new code point where a RuntimeException can be thrown (before this change it was not) as it's inside a finally and I can't see a try-catch surrounding it.

In addition in (2) there is another new point in code where a RuntimeException can be thrown (before this change the catched exception were swallowed silently) and I can't see a try-catch surrounding it.

image

For me adding a new point throwing a new RuntimeException that before did not throw it makes part of de API contract, and could lead to problems in clients using the library.

I am new to Fury code, maybe I'm wrong.

Regards

**Comment by chaokunyang** [comment]
I see, thanks for you detailed explation. This indeed introduce an API change. But it does need to throw exception here, the previous implementation is not right

**Comment by juliojgd** [comment]
Maybe it should be noted in the release notes, highlighting that here is such API change.

**Comment by chaokunyang** [comment]
> Maybe it should be noted in the release notes, highlighting that here is such API change.

Great suggestion, we should have an API change section in our release notes

**Pull request merged**
