### PR TITLE
docs: add check lint ci & fix md lint

### PR DESCRIPTION
**Pull request by yuluo-yx**
- For https://github.com/apache/fury-site/issues/155

### CODE REVIEW

**Comment by chaokunyang** [comment]
missing headers:
image

**Comment by yuluo-yx** [comment]
> missing headers
done

**Review by chaokunyang — APPROVED** [review]
LGTM

**Comment by chaokunyang** [comment]
Still missing headers:
image

**Comment by yuluo-yx** [comment]
> Still missing headers: image

yep. I find. but I add license herader

image

**Comment by yuluo-yx** [comment]
It has been solved. It was a format problem and the error reported was not accurate. @chaokunyang ptal

**Pull request merged**
