### PR TITLE
build: publish jars for fury-scala

### PR DESCRIPTION
**Pull request by pjfanning**
This PR uses https://github.com/mdedetrich/sbt-apache-sonatype to support publishing fury-scala jars to Apache's Nexus repository.

`sbt +publishSigned`

requires that you set NEXUS_USER and NEXUS_PW environment variables to provide your Apache username and password.

I have used my PR code to publish some snapshots to https://repository.apache.org/content/groups/snapshots/org/apache/fury/

### CODE REVIEW

**Comment by chaokunyang** [comment]
Hi @pjfanning , I tried to publish jar with `sbt +publishSigned`, but it failed with:
image
```java
[error] java.util.zip.ZipException: duplicate entry: META-INF/LICENSE
[error] 	at java.base/java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:259)
[error] 	at java.base/java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:115)
[error] 	at sbt.io.IO$.addFileEntry$1(IO.scala:717)
[error] 	at sbt.io.IO$.$anonfun$writeZip$6(IO.scala:726)
[error] 	at sbt.io.IO$.$anonfun$writeZip$6$adapted(IO.scala:726)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at sbt.io.IO$.writeZip(IO.scala:726)
[error] 	at sbt.io.IO$.$anonfun$archive$2(IO.scala:676)
[error] 	at sbt.io.IO$.$anonfun$archive$2$adapted(IO.scala:673)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1(IO.scala:773)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1$adapted(IO.scala:753)
[error] 	at sbt.io.Using.apply(Using.scala:28)
[error] 	at sbt.io.IO$.withZipOutput(IO.scala:753)
[error] 	at sbt.io.IO$.archive(IO.scala:673)
[error] 	at sbt.io.IO$.jar(IO.scala:638)
[error] 	at sbt.Package$.makeJar(Package.scala:229)
[error] 	at sbt.Package$.$anonfun$apply$4(Package.scala:152)
[error] 	at sbt.Package$.$anonfun$apply$4$adapted(Package.scala:150)
[error] 	at sbt.util.Tracked$.$anonfun$outputChangedW$1(Tracked.scala:129)
[error] 	at sbt.Package$.apply(Package.scala:162)
[error] 	at sbt.Defaults$.$anonfun$packageTask$1(Defaults.scala:1918)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] (Compile / packageSrc) java.util.zip.ZipException: duplicate entry: META-INF/LICENSE
[error] Total time: 6 s, completed Sep 26, 2024, 9:56:47 PM
```

I've already upgrade sbt to 1.10.2

Is there something that I get wrong?

**Comment by chaokunyang** [comment]
Thanks @pjfanning , I managed run command `` with your patch.  But it still didn't upload jar to nexus. It installed jar locally:
image
Is there other things that I need to do to upload jar to apache nexus?

**Comment by pjfanning** [comment]
This plugin is installed in the project and its docs describe the publishing steps:

https://github.com/xerial/sbt-sonatype

**Comment by chaokunyang** [comment]
Thanks @pjfanning , it works now

**Comment by pjfanning** [comment]
@chaokunyang looks like you released the scala jars - see https://repo1.maven.org/maven2/org/apache/fury/fury-scala_2.13/

With sbt-sonatype, `sbt sonatypeBundleRelease` does a full release.

For an RC that needs to be voted on, you can use other commands.

In Apache Pekko releases, we use

`sbt "sonatypePrepare; sonatypeBundleUpload; sonatypeClose"`

This gets the jars uploaded to the repository.apache.org staging repo.

You don't put your java jars in staging area, so if you want the pre-staged area, you could use 
`sbt "sonatypePrepare; sonatypeBundleUpload"`

**Comment by pjfanning** [comment]
In Apache Pekko builds, we've modified our sbt setup to stop users accidentally running the full release to Maven Central.

**Comment by chaokunyang** [comment]
My bad, I didn't realized that it will execute `sonatypeRelease`. This is my first time to use sbt to upload jars. So could we still release 0.8.0, Or we drop this release and start to release 0.9.0?

**Comment by pjfanning** [comment]
I think it's ok to continue with the 0.8.0 RC. We can worry about getting these jars removed from Maven Central if the vote fails.

**Comment by chaokunyang** [comment]
> I think it's ok to continue with the 0.8.0 RC. We can worry about getting these jars removed from Maven Central if the vote fails.

I see, thanks. Let's continue the discussion in the email thread.

**Pull request merged**
